# Generated by Django 4.0.3 on 2022-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_date_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
